# Generated by Django 4.0.6 on 2022-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_userprofuile_education_userprofuile_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofuile',
            name='currently_hacking_on',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofuile',
            name='currently_learning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofuile',
            name='skills_language',
            field=models.TextField(blank=True),
        ),
    ]
